
on:
  - pull_request

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: link
        run: npm link

      - name: execute help
        run: clup --help